jobs:
  # track deployments on the environment
- deployment: PowerShellScript
  displayName: powershell script
  pool:
    vmImage: 'pool1'
  # creates an environment if it doesn't exist
  environment: 'env1'
  strategy:
    # default deployment strategy, more coming...
    runOnce:
      deploy:
        steps:
        - script: Write-Host "Hello World"