jobs:
  # track deployments on the environment
- deployment: PowerShellScript
  displayName: powershell script
  # creates an environment if it doesn't exist
  environment: 'env1.akshaya-desktop'
  strategy:
    # default deployment strategy, more coming...
    runOnce:
      deploy:
        steps:
        - script: Write-Host "Hello World"